# -*- coding: utf-8 -*-
"""FMIMRAZ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yY6Mcb0M3jwIa4pQ2keKwUXZTkLYYR_n
"""

import pandas as pd

df = pd.read_csv('iris.csv')
df

X = df.drop(columns='species')
y = df['species']

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=23, metric = "manhattan")
clf.fit(X, y)
y_pred = clf.predict(X_test)

from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
import math
import numpy as np

acc = cross_val_score(clf, X, y, cv = 5, scoring='accuracy').mean()

cm = confusion_matrix(Y_test, y_pred)
print("Точность = ", acc)
print("Матрица запутанности: \n", cm)

import seaborn as sns
import matplotlib.pyplot as plt

irisTest = X_test.assign(species = Y_test)

sns.set_style("whitegrid")

sns.FacetGrid(irisTest, hue ="species",
              height = 5).map(plt.scatter,
                              'sepal_length',
                              'petal_length').add_legend()

irisPred = X_test.assign(species = y_pred)

sns.set_style("whitegrid")

sns.FacetGrid(irisPred, hue ="species",
              height = 5).map(plt.scatter,
                              'sepal_length',
                              'petal_length').add_legend()

